name: VercelCD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: develop
      url: 'doavai.vercel.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy DEV
  
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'doavai.vercel.com'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy Production




